.TH COMEDIRECORD "1" "Jan 2014" "comedirecord 1.27" "User Commands"
.SH NAME
comedirecord \- an oscilloscope for COMEDI
.SH SYNOPSIS
.B comedirecord
[\fIOPTION\fR]... FILENAME
.SH DESCRIPTION
A simple oscilloscope application which displays data from COMEDI
DAQ cards. It can run with multiple idential cards and save the data
in a single text file which then can be imported into OCTAVE, scilab,
gnuplot, MATLAB and other data ploting applications.
A mains notch filter, a lowpass, a highpass and a DC filter can be
used to improve the data being displayed. However
the data is always saved unfiltered in its original form
and at the sampling rate specified with
the -r option. Comedirecord can
also listen on a TCP port which allows the logging of additional
information from external programs or just logging comments
connected via telnet.
.TP
\-i
ignores last saved configuration and resets all settings to
default values which which should work with most DAQ boards.
.TP
\-r SAMPLINGRATE
sets both the internal sampling rate and the sampling
rate for the data files. If a slower timebase is selected
then the displayed data is averaged. The saved data has always
the sampling rate specified here.
.TP
\-c CHANNELS
sets the number of channels
.TP
\-f FORMAT
set data format for ASCII files: 0 = space separated, 1 = csv
.TP
\-n FREQUENCY
sets the notch filter frequency to remove unwanted mains interference.
.TP
\-a FREQUENCY
sets the lowpass filter frequency to smooth out signals
.TP
\-b FREQUENCY
sets the highpass filter frequency to remove low frequency baseline shifts
.TP
\-x DEV,CH,MAXF
displays a Fourier transform of channel CH of device DEV with maximum
frequency MAXF.
.TP
\-d DEVICES
sets the maximum number of comedi devices (default is that all
connected COMEDI devices are used)
.TP
\-l LOWEST_COMEDI_DEV_NUM
sets lowest comedi device number which will be
probed (default is 0 which means that /dev/comedi0 will be probed first).
.TP
\-p PORT
sets the TCP port for receiving external data, for example via telnet.
This data will be appended in the data files after the last channel sample.
.TP
\-t TEXT_APPENDED
default text appended when external data via TCP hasn't been received
or when external data has a lower sampling rate than the comedirecord.
This is useful for gnuplot or octave so that the number of columns
is constant.
.SH "SEE ALSO"
More documentation can be found on
http://www.linux-usb-daq.co.uk/software2/comedi-record/
in particular examples describing how to import data into octave, gnuplot
or MATLAB.
.SH AUTHOR
comedirecord was written by Bernd Porr <tech@linux-usb-daq.co.uk>.
